runtime: python39
entrypoint: gunicorn -b :$PORT app:app

env_variables:
  BINANCE_API_KEY: 'your_binance_api_key'
  BINANCE_API_SECRET: 'your_binance_api_secret'

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto
